# Generated by Django 5.1.4 on 2025-02-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_remove_movie_release_date_movie_trailer_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='release_date',
        ),
    ]
