# Generated by Django 5.1.4 on 2025-02-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_remove_season_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/crews/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/movie/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/series/'),
        ),
    ]
