# Generated by Django 5.1.4 on 2025-02-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_alter_downloadfile_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='choosen_country',
        ),
        migrations.RemoveField(
            model_name='series',
            name='choosen_country',
        ),
    ]
