# Generated by Django 5.1.4 on 2025-03-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0034_sitesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='domain_url',
            new_name='download_domain',
        ),
    ]
