# Generated by Django 5.1.4 on 2025-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0035_rename_domain_url_sitesetting_download_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='age_category',
            field=models.CharField(blank=True, choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5, null=True),
        ),
    ]
