# Generated by Django 5.1.4 on 2025-04-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0037_alter_downloadfile_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Short Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_descriptions', to='movie.series', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'Short Description',
                'verbose_name_plural': 'Short Descriptions',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه'), ('saturday', 'شنبه'), ('sunday', 'یک\u200cشنبه')], max_length=10, verbose_name='Day of Week')),
                ('air_time', models.TimeField(blank=True, null=True, verbose_name='Air Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='movie.series', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'Weekly Schedule',
                'verbose_name_plural': 'Weekly Schedules',
                'ordering': ['day_of_week'],
                'unique_together': {('series', 'day_of_week')},
            },
        ),
    ]
